apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong-database
          image: postgres:9.6-alpine
          env:
            - name: POSTGRES_USER
              value: "kong"
            - name: POSTGRES_DB
              value: "kong"
            - name: POSTGRES_PASSWORD
              value: "kong"
          ports:
            - containerPort: 5432
        - name: kong-bootstrap
          image:  kong:2.5.0-alpine
          depends_on: postgres
          env:
            - name: KONG_DATABASE
              value: "KONG_DATABASE" 
            - name: KONG_PG_HOST
              value: "kong-database" 
            - name: KONG_PG_DATABASE
              value: "kong" 
            - name: KONG_PG_USER
              value: "kong" 
            - name: KONG_PG_PASSWORD
              value: "kong" 
          command: ["kong migrations bootstrap"]
        - name: kong
          image: kong:2.5.0-alpine
          hostname: kong
          depends_on: kong-bootstrap
          env:
            - name: KONG_DATABASE
              value: "postgres"
            - name: KONG_PG_HOST
              value: "kong-database"
            - name: KONG_PG_DATABASE
              value: "kong" 
            - name: KONG_PG_USER
              value: "kong" 
            - name: KONG_PG_PASSWORD
              value: "kong" 
            - name: KONG_PROXY_ACCESS_LOG
              value: '/dev/stdout'
            - name: KONG_ADMIN_ACCESS_LOG
              value: '/dev/stdout'
            - name: KONG_PROXY_ERROR_LOG
              value: '/dev/stderr'
            - name: KONG_ADMIN_ERROR_LOG
              value: '/dev/stderr'
            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
          command:
            - "kong start"
          ports:
            - "8000:8000"
            - "8443:8443"
            - "8001:8001"
            - "8444:8444"
