apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: kong
            - name: POSTGRES_PASSWORD
              value: kong
            - name: POSTGRES_USER
              value: kong
          image: postgres:9.6-alpine
          name: kong-database
          ports:
            - containerPort: 5432
          resources: {}
      hostname: kong-database
      restartPolicy: Always
status: {}
